# Generated by Django 3.2.17 on 2023-02-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_customer_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publications', models.CharField(max_length=50, null=True)),
                ('edition', models.CharField(max_length=10, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
                ('book_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Books_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publications', models.CharField(max_length=50, null=True)),
                ('edition', models.CharField(max_length=10, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
                ('book_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.bookstore')),
            ],
        ),
        migrations.CreateModel(
            name='Books_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publications', models.CharField(max_length=50, null=True)),
                ('edition', models.CharField(max_length=10, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
                ('book_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.library')),
            ],
        ),
    ]
