# Generated by Django 3.2.17 on 2023-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_books_library_books_store_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_library',
            name='book_owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books_store',
            name='book_owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books_user',
            name='book_owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
