# Generated by Django 3.2.17 on 2023-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20230303_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoreprofile',
            name='image',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='image',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
    ]
