# Generated by Django 3.2.17 on 2023-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20230305_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreprofile',
            name='image',
            field=models.FileField(default='Book/images/profileicon.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.FileField(default='Book/images/profileicon.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='libraryprofile',
            name='image',
            field=models.FileField(default='Book/images/profileicon.jpg', upload_to='profiles'),
        ),
    ]
