# Generated by Django 3.2.17 on 2023-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20230305_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='libraryprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
