# Generated by Django 3.2.17 on 2023-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20230307_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(default='profilepicon.jpg', upload_to='profiles'),
        ),
    ]
