# Generated by Django 3.2.17 on 2023-03-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_alter_customerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_user',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
