# Generated by Django 3.2.17 on 2023-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_books_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_user',
            name='look',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
