# Generated by Django 3.2.17 on 2023-03-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_books_user_look'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_user',
            name='look',
        ),
    ]
